### PR TITLE
type definition

### PR DESCRIPTION
**Pull request by Sayan751**
This PR contains the type definition for this package.
Related to #37, #43, and https://github.com/aurelia/aurelia/issues/847

### CODE REVIEW

**Comment by zewa666** [comment]
Nice one @sayan751. This certainly will help TS users

**Comment by Sayan751** [comment]
Thanks @zewa666 for taking a look :) Good catch, will make the change

**Comment by Sayan751** [comment]
@zewa666 done :)

**Comment by zewa666** [comment]
Lgtm

**Comment by Sayan751** [comment]
Thanks @perrin4869  :)

**Pull request merged**
